version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    network_mode: "host"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "<PASS_HERE>"
      MONGO_INITDB_DATABASE: stark
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb:/data/db
      - ./mongod.conf:/etc/mongod.conf
    entrypoint: [ "mongod", "--config", "/etc/mongod.conf" ]
  node:
    build: .
    container_name: node
    restart: always
    network_mode: "host"
    environment:
      - MONGODB_URL=mongodb://root:<PASS_HERE>@127.0.0.1:27017 # mongodb link
      - GRAPHQL_URL=http://127.0.0.1:8081/v1/graphql # url for parse
      - NEW_INSERT_CONTRACTS=true # insert new contracts using 30m timer
      - CORES=10 # num of cores for cache workers
    volumes:
      - ./client:/node/client
      - ./server:/node/server
  parser:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: parser
    restart: always
    network_mode: "host"
    environment:
      - MONGODB_URL=mongodb://root:<PASS_HERE>>@127.0.0.1:27017 # mongodb link
      - GRAPHQL_URL=http://127.0.0.1:8081/v1/graphql # url for parse
      - SLOW_MODE=false # slow mode for parse new/all contracts
      - PARSE_ALL_CONTRACTS=false # parse old contracts for db
      - NEW_INSERT_CONTRACTS=true # insert new contracts using 30m timer
      - UPDATE_CONTRACTS=false # update every 1 day all contracts for db
    volumes:
      - ./parser:/node/parser
